[project]
name = "pumpwood-streamlit"
version = "{VERSION}"
description = "Package to deploy Streamlit at Pumpwood Systems"
readme = "README.md"
requires-python = ">=3.6"
license = { text = "BSD-3-Clause License" }
authors = [
    {name = "André Andrade Baceti", email = "a.baceti@murabei.com"}
]
urls = { Homepage = "https://github.com/Murabei-OpenSource-Codes/pumpwood-streamlit-pkg" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "streamlit",
    "extra-streamlit-components",
    "streamlit-cookies-controller",
    "pandas",
    "lxml",
    "pyarrow",
    "pumpwood-communication>=2.2.4",
    "openpyxl",
    "loguru>=0.7.3",
]

[tool.poetry]
packages = [{include = "pumpwood_streamlit", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 79
indent-width = 4

exclude = [
  "secrets/",
  "__init__.py",
  "setup_template.py",
  "setup.py"
]

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "D",
    "I",
    "PD",
    "N",
    "S",
]
ignore = [
  "E402", "N806", "I001"
]

preview = true

[tool.ruff.format]
indent-style = "space"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
no-sections = true

[dependency-groups]
docs = [
    "mkdocs (>=1.6.1,<2.0.0)"
]
